# Generated by Django 2.2.2 on 2019-06-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_1', models.CharField(max_length=13)),
                ('telefone_2', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
