# Generated by Django 2.2.2 on 2019-06-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contato.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endereco.Endereco')),
            ],
        ),
    ]
