# Generated by Django 2.2.2 on 2019-06-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=80, null=True)),
                ('bairro', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('municipio', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
